### ISSUE TITLE
Develop an API for streams

### ISSUE THREAD

**Issue by christophehenry** [jaywink/socialhome#194]
I open this issue to discuss implementation of an API for streams as part of #193. Though, I have no clear idea where to start with and how to do it. So @jaywink, I leave the implementation specification details to you, if you're ok.

**Comment by jaywink** [comment]
I think that is a good idea yes, I have some plans evolving in my head. I'll document to this issue a way forward with this that could work 👍 Related also to (larger issue) #139 .

**Comment by jaywink** [comment]
@christophehenry, everything should be there now for public, followed and tag streams.

Profile streams coming a bit later.
