### ISSUE TITLE
Please don't jump after deleting content

### ISSUE THREAD

**Issue by felixplesoianu** [jaywink/socialhome#204]
Hello! After deleting content from my profile, the view jumps to the public stream, which is set as my landing page for now. I think the profile should remain displayed in this situation regardless of what's in preferences. It makes sense from an UI perspective, and would reduce confusion when editing a large profile page (not the case for me yet). Thank you.

**Comment by jaywink** [comment]
Implemented:
* Delete triggered from stream or profile will redirect back to the same page after delete.
* Delete triggered from the content detail itself will redirect to user set landing page.

Also at the same time made create/update redirect to the respective content detail that was created/updated.

@felixplesoianu if you think this doesn't satisfy the issue you raised, please reopen. Thanks again for reporting, this (especially create/update) annoyed me for a long time too ;)
