### ISSUE TITLE
Replies appear broken

### ISSUE THREAD

**Issue by felixplesoianu** [jaywink/socialhome#217]
After the release of 0.2.0, clicking Save after typing in a reply just keeps me on the same page, and the reply never seems to register. I tried in both Firefox and Chromium. Creating content however works just fine.

**Comment by jaywink** [comment]
Thanks for the heads up, will fix asap 👍

**Comment by jaywink** [comment]
OK fix pushed to socialhome.network. Will write tests later and merge the fix to master. Sorry about this, pushed out the form change yesterday a bit hastily as I found the security issue while working on the form..

Thanks for reporting!
