### ISSUE TITLE
Add an editorconfig file

### ISSUE THREAD

**Issue by christophehenry** [jaywink/socialhome#235]
Could be a good idea to enforce some rules.

**Comment by christophehenry** [comment]
Hmm... I'm disappointed... I hoped [there would be much more properties](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties). Maybe it's not that good, then.  But I suppose we can distribute a PyCharm configuration file?

**Comment by christophehenry** [comment]
Oh! NVM, there's already one. Héhé ':D

**Comment by jaywink** [comment]
Related though #187 - need to have a proper eslint config.
