### ISSUE TITLE
Make Karma, Webpack and Travis to work

### ISSUE THREAD

**Issue by christophehenry** [jaywink/socialhome#261]
I think it's a good time to raise an issue. I'm still struggling trying to find the correct configuration for Karma and Webpack. This is more or less a blocking point for #254. In the current state of #254, `npm run test`fails locally *on my computer* with error:

```
TypeError: undefined is not an object (evaluating 'plugin.install')
```

which seems to be related to [this line](https://github.com/jaywink/socialhome/pull/254/files#diff-45dd55e9842ac5b54f087468655658d5R10) which, if commented, make the tests pass.

It fails on @jaywink with error:

```
SyntaxError: Unexpected token 'const'"
```

And [it fails on Travis with yet another error](https://travis-ci.org/jaywink/socialhome/jobs/265493734#L1381). Somehow, the link between Webpack and Karma seems to be broken. For instance, I found three days ago, that I had to use [a `.babelrc`](https://github.com/jaywink/socialhome/pull/254/files#diff-e56633f72ecc521128b3db6586074d2c) file to make Karma to work with `vue-masonry`. Previously to that, I had:

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at webpack:///node_modules/vue-masonry/src/masonry.plugin.js:5:1 <- socialhome/streams/app/tests/main.tests.js:11622
```
which seems to be the same error that @jaywink currently faces. Karma and/or Webpack seem to be very sensible to environment though I have no idea yet of what makes them that fragile.

None of what I've found so far on internet has been helpful. I've lost all hope by now. Thus, if anybody has any idea how to solve the problem, I open. I won't be able to progess if this is not solved.

**Comment by jaywink** [comment]
CLosing https://github.com/christophehenry/socialhome/pull/1
