### ISSUE TITLE
autoprefixer-core was deprecated, use autoprefixer instead

### ISSUE THREAD

**Issue by autogestion** [jaywink/socialhome#309]
"npm run dev" fails with this warning

**Comment by jaywink** [comment]
This should just be a warning, grunt should still build the bundle OK, at least it does for me. Can you post a full log please if it is failing totally?

The node libs management is in a mess atm, since we're using grunt and webpack at the same time. It's possible the `autoprefixer` package wont even be kept when grunt is retired, so updating it is probably not worth the time.

**Comment by autogestion** [comment]
Full log:

`(st) mk@mk:~/dev/an/socialhome$ npm run dev

> socialhome@0.1.0 dev /home/mk/dev/an/socialhome
> ./node_modules/grunt/bin/grunt dev && ./node_modules/webpack/bin/webpack.js

autoprefixer-core was deprecated. Use autoprefixer package.
Running "sass:dev" (sass) task
>> Error: File to import not found or unreadable: ../../../bower_components/bootstrap/scss/_variables.scss.
>>        Parent style sheet: /home/mk/dev/an/socialhome/socialhome/static/sass/variables.scss
>>         on line 1 of socialhome/static/sass/variables.scss
>> >> @import "../../../bower_components/bootstrap/scss/_variables.scss";
>>    ^
Warning:  Use --force to continue.

Aborted due to warnings.


Execution Time (2017-09-26 11:18:33 UTC+3)
loading tasks  362ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 84%
sass:dev        67ms  ▇▇▇▇▇▇▇▇ 16%
Total 430ms

npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! socialhome@0.1.0 dev: `./node_modules/grunt/bin/grunt dev && ./node_modules/webpack/bin/webpack.js`
npm ERR! Exit status 6
npm ERR! 
npm ERR! Failed at the socialhome@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mk/.npm/_logs/2017-09-26T08_18_33_723Z-debug.log
`

**Comment by christophehenry** [comment]
It's not the problem. My guess is you forgot to run `bower install`.

**Comment by christophehenry** [comment]
Do you still have the problem or can this be closed?

**Comment by autogestion** [comment]
problem fixed by bower install

**Comment by jaywink** [comment]
Great! 👍
