### ISSUE TITLE
[VueJS] Notifications

### ISSUE THREAD

**Issue by christophehenry** [jaywink/socialhome#322]
With the Vue front-end going big, I think it's time to properly handle notifications. We have a few use-cases that need a proper error hadling. Hopefully, VueJS has tons of plugins including a bunch of notification libraries listed [here](https://github.com/vuejs/awesome-vue#notification). I've excluded libraries that received no commit for more than 3 months and those not proposing a proper demo to narrow the choice to:

* [Vue toasted](https://github.com/shakee93/vue-toasted)
* [Vue notification](https://github.com/euvl/vue-notification)
* [Vue snotify](https://github.com/artemsky/vue-snotify)

In my opinion, Vue snotify is the best. It's pretty, it's rather small and offers fancy features. But it's also opiniated regarding design.

What do you think?

**Comment by jaywink** [comment]
So by notifications you mean things like "share action failed", not a notifications menu listing peoples actions like replies, shares and reactions?

If the latter then it's blocked until we have notifications in the backend too. Currently all notifications are just via email.

If you meant the former then yes, would be nice to have some information delivered to user on the event of an error happening, for example failing to load the stream or share content. I'll leave it up to you which library, but visually I would like it to fit into the current UI, so probably no huge boxes like in some of these demos. Colour is ok, but the notifications should be relatively simple and not "in your face" as the UI is simple too.

Thanks for looking into these! I'll add a link to this issue in #202 .

**Comment by christophehenry** [comment]
#398 adding notifications is merged. Closing.
