### ISSUE TITLE
Remote user profile save should fix image urls

### ISSUE THREAD

**Issue by jaywink** [jaywink/socialhome#327]
All our `Profile` image urls should be absolute. Some remote delivered profile urls are relative. We should fix them, for example the following:

    /assets/foo.bar

becomes

    https://domain.tld/asserts/foo.bar

The domain.tld comes from the remote profile handle.

**Comment by amirkarimi** [comment]
I would like to work on this.

**Comment by jaywink** [comment]
@amirkarimi Awesome!

Yes, you got it right. Basically the lines are [here](https://github.com/jaywink/socialhome/blob/9a83abcfb9cb43139f5fb86a437926358730536e/socialhome/users/models.py#L281-L283):

    "image_url_large": safe_text(remote_profile.image_urls["large"]),
    "image_url_medium": safe_text(remote_profile.image_urls["medium"]),
    "image_url_small": safe_text(remote_profile.image_urls["small"]),

If the `remote_profile.image_urls` urls contain a relative url, it needs to be made absolute using the domain of `remote_profile.handle`. We can safely assume https is the protocol for all remote urls.

**Comment by amirkarimi** [comment]
Sorry for the delay. I started working on this issue but realized that it's been implemented [here](https://github.com/jaywink/socialhome/blob/master/socialhome/users/models.py#L210). `safer_image_url` will make relative the URLs absolute so as long as `safer_image_url_(small|medium|large) is used the URLs would be OK. In another world, it's been made absolute on each attribute access not on load/save.

The question is; providing the above information, is this issue still valid? If so, to close this issue, should we:
- Make URLs absolute at load time [here](https://github.com/jaywink/socialhome/blob/9a83abcfb9cb43139f5fb86a437926358730536e/socialhome/users/models.py#L281-L283)
- Remove `safer_image_url_*` and replace all usages with `image_url_*`

**Comment by jaywink** [comment]
Yes you are completely right. Sorry for not mentioning that in the issue, I was obviously aware of the `safer_` wrappers but forgot to mention them in the issue :(

The aim is to ensure `image_url_*` fields always contain an absolute URL, so we don't have to wrap them in any way. Right now this is a problem in the REST API since we don't use the wrappers there at all (it would add more complexity to each serialization).

To close this issue it's necessary to convert the remote profile url to an absolute one, as indicated in your first option. You can re-use the "safer_" code if you want 👍 Then we can remove the "safer_" properties and just use the image url fields directly in the UI. That is kind of optional though, not directly related to this issue.

Btw, thinking about it, instead of putting the conversion into parsing the remote profile, it could also be in `Profile` save. Our local urls from picture upload are always absolute currently, but one central place might still be better. Leave it up to you which one you think is better.

Thanks for working on this! It will make Profile API image urls more reliable.

**Comment by jaywink** [comment]
Fixed by #348
