### ISSUE TITLE
Change the envelope icon for replies in streams

### ISSUE THREAD

**Issue by Vir-Cotto** [jaywink/socialhome#339]
In the streams UI, we use an envelope to represent replies, which are comments.

Envelopes usually indicate email, or sometimes notifications. We're already using FontAwesome- why not switch to the comment icon http://fontawesome.io/icon/comments/

**Comment by jaywink** [comment]
Sounds an ok change to me. What do you think @christophehenry, you've been interested in design tweaks?

**Comment by christophehenry** [comment]
I agree with @Vir-Cotto.

**Comment by jaywink** [comment]
OK, let's change it then! @Vir-Cotto feel free to make a PR 👍 Note that there are several places (current stream, vue stream), searching through with the old class is the best way to find them.

**Comment by jaywink** [comment]
Closed via #347
