### ISSUE TITLE
Login - allow email address in addition to nickname as login id

### ISSUE THREAD

**Issue by valvin1** [jaywink/socialhome#377]
During the registration process we create an account with email and choose a nickname. 

I'm using Kee extension to register my password and it has detected my e-mail address has login. So on the first login I had an error about wrong password.

In reality it was because i try to use my email address to login instead of my nickname.

Having both nickname and e-mail address should avoid this kind of issue.

**Comment by jaywink** [comment]
This was just a configuration issue so fixed now! Not yet deployed to socialhome.network though but coming at some point, latest when release is done. Thanks for raising this! 👍
