### ISSUE TITLE
Some fixtures would be nice

### ISSUE THREAD

**Issue by Vir-Cotto** [jaywink/socialhome#392]
When you're playing with a dev instance of socialhome, it would be nice to have some fixtures that include some users (alice, bob, carol, dave) and some content of various types.

**Comment by jaywink** [comment]
Most definitely, this would be useful. If someone wants to work on this, please don't use JSON fixtures but generate a management command that creates data using factories instead. Fixtures break easily on schema changes and are not flexible if we want to for example create different kind of data which the management command can do 👍

**Comment by jaywink** [comment]
So @Vir-Cotto I added a management command, see [here](https://socialhome.readthedocs.io/en/latest/development.html#generating-dummy-content). Please expand as necessary for whatever type of content you need. If not sure how to add different types of content you might need to the list of created content, please don't be afraid to ask. Would be good if it creates all kinds of content and maybe profile relationships too, right now it's very simple, just creates 100 public content using 100 public (dummy remote) profiles.
