### ISSUE TITLE
Circus and systemd

### ISSUE THREAD

**Issue by geosphere** [jaywink/socialhome#397]
Hi there!
Do you have any solutions for correct making systemd script to start Circus on Debian?

**Comment by jaywink** [comment]
Hi! Unfortunately currently the docs only contain [an example](https://socialhome.readthedocs.io/en/latest/installation/ubuntu.html#set-up-circus) for Upstart for one simple reason - I'm on Ubuntu 14.04 myself for my two production nodes. I don't think it will be very difficult to create the systemd configuration, but unfortunately I don't have an example for you currently. Basically, what is important is understanding it is a Python app running within a virtualenv, so python path, working directory, circusd executable ie need to be correct, just like in the upstart example we set various environment variables and call the right `circusd` binary. Pretty much the same as for example running a user virtualenv installed uWSGI would work.

I will be migrating my nodes to systemd using OS within a month or so hopefully, will update docs then. Contribution welcome before that if you get a node running! You can submit a PR to the docs or paste it here.

In reality though, I would recommend in the future to use Docker for deploying Socialhome production nodes. That configuration is still being worked on though as well.

Thanks for raising.

**Comment by geosphere** [comment]
Ok, this systemd service config working fin:
```
cat /etc/systemd/system/socialhome.service

[Unit]
Description=Socialhome Django script 
After=syslog.target network.target

[Service]
Environment=DJANGO_SETTINGS_MODULE="config.settings.production"
Environment=PYTHONPATH="/home/socialhome/socialhome"
Environment=SOCIALHOME_HOME="/home/socialhome"
Environment=RQWORKER_NUM=5
Environment=VIRTUAL_ENV=/home/socialhome/.virtualenvs/socialhome

User=socialhome
Group=socialhome

WorkingDirectory=/home/socialhome/socialhome
ExecStart=/home/socialhome/.virtualenvs/socialhome/bin/circusd /home/socialhome/socialhome/config/circus.ini
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by jaywink** [comment]
Thanks @geosphere ! Added to docs in https://github.com/jaywink/socialhome/commit/9f271f85492f557a77d799e7bcd63bc423414cc4.
