### ISSUE TITLE
Add JSON Webfinger support

### ISSUE THREAD

**Issue by Zauberstuhl** [jaywink/socialhome#405]
Hi,

just discovered that socialhome still doesn't support the new webfinger layout.

`%s/webfinger?q=acct:%s` vs `%s/.well-known/webfinger?resource=acct:%s`

Is that an issue or don't want it ;) ?

related to https://github.com/ganggo/federation/pull/6

**Comment by jaywink** [comment]
@Zauberstuhl I have not been able to keep up with all the changes in the diaspora protocol, this is just one of the items in the backlog waiting to be implemented. Thanks for logging 👍 

Logged as jaywink/federation#108
