### ISSUE TITLE
Namespace (or path) of EmailAddress  class

### ISSUE THREAD

**Issue by mohammadh73** [jaywink/socialhome#475]
I just forked the repository and I tried to follow installation guides. In [this step](http://socialhome.readthedocs.io/en/latest/development.html#creating-a-user) we must confirm user's email through **EmailAddress** class:
```EmailAddress.objects.all().update(verified=True)```
The problem is I don't know how to import it! There is no namespace or specific path of the class and I can't find it in `socialhome.users.models`. 
I think it's better to add a detail of class location or namespace.
e.g. `from foo import EmailAddress`

**Comment by jaywink** [comment]
Thanks for raising! I clarified the docs in https://github.com/jaywink/socialhome/commit/d6209484e4594e893c532e1a0552084c2aa1724b - hopefully better now!
