### ISSUE TITLE
API UI not working

### ISSUE THREAD

**Issue by ellisist** [jaywink/socialhome#509]
The docs mention a browsable API endpoint at `/api/` but both on my local development version and going to socialhome.network/api/ in the browser throws an error.

Having looked into Swagger a little bit, it looks like the problem is the `base.html` template was deleted in favor of having just `index.html` in Swagger v. 2.2.0. Testing locally, I found two possible solutions:
1. Deleting Socialhome's `rest_framework_swagger/index.html`. This allows the generated Swagger page to show up without customization.
2. Copying Swagger's `index.html` from the packages to the Socialhome templates and modifying it. This allows for customization, though is maybe less readable.

This is clearly a problem that rose from a change to Swagger, but should be easy enough to fix. If I know what fix is preferred I'd be happy to submit a PR.

**Comment by jaywink** [comment]
Thanks for noticing! Should maybe have a test case to check the API docs render. Bonus points for adding one if you do a PR ;)

I would prefer solution 2 as it allows keeping the customization we had. Mainly currently I think there is a link back to the front page of the particular instance. Creates a slightly more integrated feeling. But, no strong opinion here, I'll let you make the judgement on how you are prepared to fix it. A PR would most definitely be nice.
