### ISSUE TITLE
Can't migrate DB

### ISSUE THREAD

**Issue by christophehenry** [jaywink/socialhome#52]
When exacting `python manage.py migrate` I get the error:

``` python
django.db.utils.OperationalError: FATAL: the role "augier" doesn't exists
```

**Comment by jaywink** [comment]
Are you sure the role exists in PostgreSQL? Here are the commands I've used:

    sudo su - postgres
    createuser -s -P rolename
    createdb -O rolename dbname

Of course the role / db / pass needs to match in `env.local`.

**Comment by jaywink** [comment]
(thanks for trying Socialhome btw! :))

**Comment by christophehenry** [comment]
I created the role `socialhome` as stated in documentation. What I don't understand is why Django uses `augier` as a role. Is there a setting somewhere?

> (thanks for trying Socialhome btw! :))

You're welcome. I'm tryiing to improve my Django skills :)

**Comment by jaywink** [comment]
`DATABASE_URL=postgres://socialhome:socialhome@127.0.0.1:5432/socialhome`

That should just work, unless you've changed it. Do a `echo $DATABASE_URL` in the shell - I'm guessing you get something else which is for some other app, where you use `augier`?

I might change that env variable to `SOCIALHOME_DATABASE_URL` if this is the case.

**Comment by christophehenry** [comment]
If I run `./manage.py --load-env migrate`, I get:

```
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

**Comment by jaywink** [comment]
Sorry, I totally forgot about `--load-env` being required since I usually export the values to the shell. Not sure why I even added a flag for it. I changed it now in master, it will always try to load `env.local` if it exists (and warn if it doesn't).

Also clarified configuration a bit: https://github.com/jaywink/socialhome#configure

Basically `SECRET_KEY` you must set yourself. It's quite common to leave it empty so that there is less risk of developers pushing production apps with some default secret key.

Hope things start rolling. AFAIK you're the first one beside me setting this up so the instructions are ... lacking :)

**Comment by christophehenry** [comment]
Now, I have 

```
ImportError: cannot import name 'send_document'
```

:/

**Comment by christophehenry** [comment]
NVM. I did a `pip install -r requirements/local.txt`. Everything's ok, now.

**Comment by christophehenry** [comment]
I suppose the [settings](https://github.com/jaywink/socialhome#settings) section of documentation isn't needed anymore.

**Comment by jaywink** [comment]
I think you pulled but didn't install requirements? That is a new function in Social-Federation, required since yesterday 😁
-- 
Jason Robinson
https://jasonrobinson.me

**Comment by christophehenry** [comment]
It's a bit deceiving:

![](https://lut.im/GFB9xd1Anj/Ue7D9oJyc4kmfZk1.png)

I suppose there's a `grunt compile` or something?

**Comment by jaywink** [comment]
Did you do `grunt dev` and it gave no errors? 

And using `python manage.py runserver` to run and DEBUG is set to True?
-- 
Jason Robinson
https://jasonrobinson.me

**Comment by christophehenry** [comment]
Yes.

**Comment by jaywink** [comment]
Hmm well that is mysterious. I cloned a fresh copy and followed the instructions to the letter, only changing the DB url and SECRET_KEY in env.local. Statics load fine.

![selection_301](https://cloud.githubusercontent.com/assets/1174866/18445223/3f11455c-7925-11e6-8acf-343a3293dffa.png)

Did you tweak some settings? Does `socialhome/static` contain built resources, ie `js/project.css` and `js/project.js`? What does the browser actually give for them, 404?
