### ISSUE TITLE
Render logged in user profile on root page

### ISSUE THREAD

**Issue by jaywink** [jaywink/socialhome#61]
Even for single user mode where landing page is a set profile, when a user is logged in, always render them their own profile on root.

The relevant place to do the redirect would be somewhere [around here](https://github.com/jaywink/socialhome/blob/9bcd575bd6dc4879dcaed903fdb6d348a99b937a/socialhome/content/views.py#L78-L78).

**Comment by masterp4dev** [comment]
Hi @jaywink, I would like to work on this. Any heads up?

**Comment by jaywink** [comment]
Hey @masterp4dev - awesome!

Basically Socialhome works in two modes - "root page mode" or "root profile mode". If a root profile is set, instead of a generic root page (`HomeView`) a set user profile page is rendered (`ProfileDetailView`). You can see this happening [here](https://github.com/jaywink/socialhome/blob/9bcd575bd6dc4879dcaed903fdb6d348a99b937a/socialhome/content/views.py#L78-L78).

What we want to change is to redirect to the **logged in user profile page** (`ProfileDetailView`) if a user is logged, always. So that has to override both the possibilities above.

The readme has instructions on how to set up an environment. If you have any question please don't hesitate to ask here or on IRC FreeNode on channel #socialhome (http://webchat.freenode.net?channels=%23socialhome&uio=d4).

**Comment by christophehenry** [comment]
Can't move the card :'(

**Comment by jaywink** [comment]
Closed via #105
